"""create_execution_holds_table"""

from alembic import op
import sqlalchemy as sa

revision = "REPLACE_WITH_GENERATED_REVISION"
down_revision = "dd16408a0433"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    CREATE TABLE IF NOT EXISTS execution_holds (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        component_uid VARCHAR(100) NOT NULL,
        project_uid VARCHAR(100) NOT NULL,
        reason_code VARCHAR(100) NOT NULL,
        status VARCHAR(50) NOT NULL DEFAULT 'active',
        cleared_by INTEGER,
        detail TEXT,
        created_at TIMESTAMP,
        updated_at TIMESTAMP
    );
    """)


def downgrade() -> None:
    op.execute("""
    DROP TABLE IF EXISTS execution_holds;
    """)