"""create_enrollments_table"""

from alembic import op

revision = "7722eaa339d2"
down_revision = "efa3ac970ca1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    CREATE TABLE IF NOT EXISTS enrollments (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        professional_id INTEGER NOT NULL,
        course_code VARCHAR(100) NOT NULL,
        path_code VARCHAR(100),
        status VARCHAR(50) NOT NULL,
        score DOUBLE PRECISION,
        completed_at TIMESTAMP WITH TIME ZONE,
        created_at TIMESTAMP,
        updated_at TIMESTAMP,
        is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
        deleted_at TIMESTAMP WITH TIME ZONE
    );
    """)


def downgrade() -> None:
    op.execute("""
    DROP TABLE IF EXISTS enrollments;
    """)