"""create_atlas_subscriptions_table"""

from alembic import op
import sqlalchemy as sa

revision = "9e2ee9f037c4"
down_revision = "1de3dbe37d73"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    CREATE TABLE IF NOT EXISTS atlas_subscriptions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        subscriber_name VARCHAR(255) NOT NULL,
        subscriber_type VARCHAR(100) NOT NULL,
        country_scope VARCHAR(100),
        access_tier VARCHAR(100),
        status VARCHAR(50) NOT NULL DEFAULT 'active',
        created_at TIMESTAMP,
        updated_at TIMESTAMP,
        is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
        deleted_at TIMESTAMP WITH TIME ZONE
    );
    """)


def downgrade() -> None:
    op.execute("""
    DROP TABLE IF EXISTS atlas_subscriptions;
    """)