"""fix_legacy_table_identities"""

from alembic import op

revision = "aad431d4e40c"
down_revision = "decef4e419ac"
branch_labels = None
depends_on = None


TABLES = [
    "materials",
    "certifications",
    "milestones",
    "notifications",
    "disputes",
    "payments",
    "tenders",
    "projects",
    "professionals",
    "components",
    "evidence",
    "inspections",
    "sensors",
    "bids",
    "audit_logs",
]


def upgrade() -> None:
    for table in TABLES:
        op.execute(f"""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = '{table}'
                  AND column_name = 'id'
                  AND is_identity = 'NO'
            ) THEN
                BEGIN
                    EXECUTE 'ALTER TABLE {table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
                EXCEPTION
                    WHEN object_not_in_prerequisite_state THEN
                        NULL;
                END;
            END IF;
        END
        $$;
        """)


def downgrade() -> None:
    pass