"""fix_legacy_table_identities"""

from alembic import op

revision = "aad431d4e40c"
down_revision = "decef4e419ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'materials'
              AND column_name = 'id'
              AND is_identity = 'YES'
        ) THEN
            ALTER TABLE materials
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        END IF;
    END
    $$;
    """)

    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'certifications'
              AND column_name = 'id'
              AND is_identity = 'YES'
        ) THEN
            ALTER TABLE certifications
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        END IF;
    END
    $$;
    """)

    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'milestones'
              AND column_name = 'id'
              AND is_identity = 'YES'
        ) THEN
            ALTER TABLE milestones
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        END IF;
    END
    $$;
    """)


def downgrade() -> None:
    pass