"""fix_twin_and_certification_schema"""

from alembic import op
import sqlalchemy as sa

revision = "bf8f6b92f126"
down_revision = "20260421_0025"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    ALTER TABLE disputes
    ADD COLUMN IF NOT EXISTS determination_hash VARCHAR(128);
    """)

    op.execute("""
    CREATE TABLE IF NOT EXISTS twin_streams (
        id SERIAL PRIMARY KEY,
        stream_key VARCHAR(120) NOT NULL UNIQUE,
        project_uid VARCHAR(100) NOT NULL,
        component_uid VARCHAR(100),
        stream_type VARCHAR(50) NOT NULL,
        created_at TIMESTAMP,
        updated_at TIMESTAMP
    );
    """)

    op.execute("""
    CREATE TABLE IF NOT EXISTS twin_events (
        id SERIAL PRIMARY KEY,
        stream_id INTEGER NOT NULL REFERENCES twin_streams(id) ON DELETE CASCADE,
        event_type VARCHAR(100) NOT NULL,
        aggregate_type VARCHAR(100),
        aggregate_uid VARCHAR(100),
        actor_email VARCHAR(255),
        payload JSONB,
        event_index INTEGER NOT NULL DEFAULT 1,
        previous_hash VARCHAR(128),
        current_hash VARCHAR(128),
        created_at TIMESTAMP,
        updated_at TIMESTAMP
    );
    """)

    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'certifications'
              AND column_name = 'id'
              AND is_identity = 'YES'
        ) THEN
            EXECUTE 'ALTER TABLE certifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
        END IF;
    EXCEPTION
        WHEN others THEN
            NULL;
    END $$;
    """)


def downgrade() -> None:
    op.execute("""
    ALTER TABLE disputes
    DROP COLUMN IF EXISTS determination_hash;
    """)

    op.execute("""
    DROP TABLE IF EXISTS twin_events;
    """)

    op.execute("""
    DROP TABLE IF EXISTS twin_streams;
    """)