"""create_shi_methods_table"""

from alembic import op
import sqlalchemy as sa

revision = "dd16408a0433"
down_revision = "aad431d4e40c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    CREATE TABLE IF NOT EXISTS shi_methods (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        version_code VARCHAR(50) NOT NULL UNIQUE,
        material_weight DOUBLE PRECISION NOT NULL DEFAULT 0,
        assembly_weight DOUBLE PRECISION NOT NULL DEFAULT 0,
        environment_weight DOUBLE PRECISION NOT NULL DEFAULT 0,
        supervision_weight DOUBLE PRECISION NOT NULL DEFAULT 0,
        active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMP,
        updated_at TIMESTAMP
    );
    """)


def downgrade() -> None:
    op.execute("""
    DROP TABLE IF EXISTS shi_methods;
    """)