"""fix_disputes_id_identity"""

from alembic import op

revision = "decef4e419ac"
down_revision = "bf8f6b92f126"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    ALTER TABLE disputes
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    """)


def downgrade() -> None:
    pass