"""create_financial_products_table"""

from alembic import op

revision = "efa3ac970ca1"
down_revision = "9e2ee9f037c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    CREATE TABLE IF NOT EXISTS financial_products (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code VARCHAR(100) NOT NULL UNIQUE,
        name VARCHAR(255) NOT NULL,
        category VARCHAR(100) NOT NULL,
        description TEXT,
        base_rate_bps DOUBLE PRECISION,
        min_shi DOUBLE PRECISION,
        active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMP,
        updated_at TIMESTAMP,
        is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
        deleted_at TIMESTAMP WITH TIME ZONE
    );
    """)


def downgrade() -> None:
    op.execute("""
    DROP TABLE IF EXISTS financial_products;
    """)